# Generated by Django 2.2.2 on 2019-06-29 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=250)),
                ('uploaded_time', models.DateTimeField(default=datetime.datetime.now)),
                ('size', models.IntegerField()),
                ('processing_status', models.IntegerField(default=1)),
            ],
        ),
    ]
