# Generated by Django 2.2.2 on 2019-06-30 07:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productview', '0002_upload_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sku', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(null=True)),
                ('created_time', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_time', models.DateTimeField(default=datetime.datetime.now)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productview.Upload')),
            ],
        ),
    ]
