# Generated by Django 2.2.2 on 2019-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productview', '0005_event_webhooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
