# Generated by Django 2.2.2 on 2019-07-02 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productview', '0007_auto_20190702_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productview.Upload'),
        ),
    ]
